config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  resources :patients
  resources :doctors do
    collection do
      get :patients_vs_days_graph
    end
  end

  resources :demo_logins do
    collection do
      post :doctor_demo_login
      post :receptionist_demo_login
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :registered_by, class_name: 'User'
  belongs_to :doctor, class_name: 'User'
  def full_name
    "#{first_name} #{last_name}"
  end

  validates :first_name, :last_name, presence: true
  validates :appointment_date, :date_of_birth, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def full_name
    "#{first_name} #{last_name}"
  end
  def full_name_and_speciality
    "#{first_name} #{last_name} - #{speciality}"
  end
  validates :role, presence: true, inclusion: { in: ['doctor', 'receptionist'] }
  validates :first_name, :last_name, presence: true
  has_many :registered_patients, class_name: 'Patient', foreign_key: 'registered_by_id'
  has_many :patients, foreign_key: 'doctor_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/demo_logins_controller.rb
class DemoLoginsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:doctor_demo_login,
                                                 :receptionist_demo_login]
  def doctor_demo_login
    user = User.find_by(email: 'demodoctor@example.com')
    sign_in(user)
    redirect_to root_path
  end

  def receptionist_demo_login
    user = User.find_by(email: 'demoreceptionist@example.com')
    sign_in(user)
    redirect_to root_path
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :verify_doctor
  def index
    @patients = current_user.patients
    @patients_by_day = @patients.group_by_day(:appointment_date).count
  end
  def patients_vs_days_graph
    @patients = current_user.patients
    @patients_by_day = @patients.group_by_day(:appointment_date).count
  end

  private
  def verify_doctor
    unless current_user.role == 'doctor'
      redirect_to root_path, alert: 'You are not authorized to view this page.'
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      if current_user.role == 'doctor'
        redirect_to doctors_path
      else
        redirect_to patients_path
      end
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  before_action :verify_patient, except: [:show]
  def index
    @patients = Patient.order(created_at: :desc)
  end
  def new
    @patient = Patient.new
  end
  def create
    @patient = Patient.new(patient_params)
    @patient.registered_by = current_user

    respond_to do |format|
      if @patient.save
        format.html {redirect_to root_path, notice: "patient created successfully"}
      else
        format.html {render 'new', status: :unprocessable_entity}
      end
    end
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])
    respond_to do |format|
      if @patient.update(patient_params)
        format.html {redirect_to patient_path, notice: "Patient updated successfully!"}
      else
        format.html {render 'edit', status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy
    redirect_to root_path, notice: "Patient deleted successfully!"
  end

  private
  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :doctor_id,
                                    :appointment_date, :date_of_birth,
                                    :allergies, :chief_complaints)
  end

  def verify_patient
    unless current_user.role == 'receptionist'
      redirect_to root_path, alert: 'You are not authorized to view this page.'
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :role,
                                 :speciality)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo_logins_helper.rb
module DemoLoginsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/doctors/_patient.html.erb
<div class="bg-white shadow-md rounded-lg p-4">
  <div class="flex justify-between items-center mb-2">
    <%= link_to patient.full_name, patient_path(patient), class: "text-indigo-500 font-medium hover:text-indigo-600" %>
    <% if patient.appointment_date %>
      <div class="text-gray-500 text-sm">
        on <%= patient.appointment_date.strftime('%B %d, %Y at %I:%M%p') %>
      </div>
    <% end %>
  </div>
</div>

app/views/doctors/index.html.erb
<div class="max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:px-8">
  <h1 class="text-2xl font-bold mb-4">Your Patients</h1>

  <div class="space-y-4">
    <% @patients.each do |patient| %>
      <%= render "doctors/patient", patient: patient %>
    <% end %>
  </div>
</div>

app/views/doctors/patients_vs_days_graph.html.erb
<div class="max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:px-8">
  <div class="bg-white shadow-md rounded-lg p-6">
    <h2 class="text-2xl font-bold mb-4">Patients Registered vs Days</h2>
    <%= column_chart @patients_by_day, xtitle: "Days", ytitle: "Patients", colors: ["#FB933D"], library: { animation: { duration: 1500 } } %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PatientsManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  </head>

  <body class="bg-gray-100 font-inter">
  <header class="bg-white shadow-md mb-8">
    <div class="max-w-7xl mx-auto py-4 px-4 sm:px-6 lg:px-8 flex justify-between items-center">
      <%= link_to 'Patient Management', root_path, class: "text-indigo-500 font-bold text-xl hover:text-indigo-600" %>
      <div class="flex items-center space-x-4">
        <% if !user_signed_in? %>
          <%#= link_to "Log In", new_user_session_url, method: "get", class: "text-gray-500 hover:text-gray-700" %>
          <%#= link_to "Sign Up", new_user_registration_url, method: "get", class: "text-gray-500 hover:text-gray-700" %>
        <% else %>
          <div class="flex items-center space-x-4">
            <div class="text-gray-500">
              Currently signed in as: <%= current_user.full_name %> (<%= current_user.role %>)
            </div>
            <%= button_to "Log Out", destroy_user_session_url, method: "delete", class: "bg-indigo-500 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded" %>
            <% if current_user.role == 'receptionist' %>
              <%= link_to "Register a new patient", new_patient_path, class: "bg-indigo-500 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded" %>
            <% else %>
              <%= link_to "See Patients vs Days Graph", patients_vs_days_graph_doctors_path, class: "bg-indigo-500 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded" %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </header>

  <% if alert || notice %>
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mb-8" data-controller="flash">
      <% if notice %>
        <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
          <strong class="font-bold">Notice:</strong>
          <span class="block sm:inline"><%= notice %></span>
        </div>
      <% end %>
      <% if alert %>
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
          <strong class="font-bold">Alert:</strong>
          <span class="block sm:inline"><%= alert %></span>
        </div>
      <% end %>
    </div>
  <% end %>

  <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <%= yield %>
  </main>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_with(model: patient, class: "space-y-4") do |form| %>
  <div>
    <%= form.label :first_name, class: "block font-medium mb-2" %>
    <%= form.text_field :first_name, class: "w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" %>
    <% if patient.errors[:first_name].any? %>
      <div class="text-red-500 text-sm" role="alert">
        <%= patient.errors.full_messages_for(:first_name).join(", ") %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :last_name, class: "block font-medium mb-2" %>
    <%= form.text_field :last_name, class: "w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" %>
    <% if patient.errors[:last_name].any? %>
      <div class="text-red-500 text-sm" role="alert">
        <%= patient.errors.full_messages_for(:last_name).join(", ") %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :date_of_birth, class: "block font-medium mb-2" %>
    <%= form.date_field :date_of_birth, class: "w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" %>
    <% if patient.errors[:date_of_birth].any? %>
      <div class="text-red-500 text-sm" role="alert">
        <%= patient.errors.full_messages_for(:date_of_birth).join(", ") %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :doctor, class: "block font-medium mb-2" %>
    <%= form.collection_select :doctor_id, User.where(role: 'doctor').order(:first_name), :id, :full_name_and_speciality, { prompt: 'Select a doctor' }, class: "w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" %>
  </div>

  <div>
    <%= form.label :appointment_date, class: "block font-medium mb-2" %>
    <%= form.datetime_field :appointment_date, class: "w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" %>
    <% if patient.errors[:appointment_date].any? %>
      <div class="text-red-500 text-sm" role="alert">
        <%= patient.errors.full_messages_for(:appointment_date).join(", ") %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label "Any Allergies?", class: "block font-medium mb-2" %>
    <%= form.text_area :allergies, class: "w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" %>
  </div>

  <div>
    <%= form.label "Chief Complaints:", class: "block font-medium mb-2" %>
    <%= form.text_area :chief_complaints, class: "w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" %>
  </div>

  <div>
    <%= form.submit class: "bg-indigo-500 hover:bg-indigo-600 text-white font-medium py-2 px-4 rounded w-full" %>
  </div>
<% end %>

app/views/patients/_patient.html.erb
<div class="bg-white shadow-md rounded-lg p-4">
  <div class="flex justify-between items-center mb-2">
    <%= link_to patient.full_name, patient_path(patient), class: "text-indigo-500 font-medium hover:text-indigo-600" %>
    <div class="text-gray-500 text-sm">
      Assigned to Dr. <%= patient.doctor.full_name %>
    </div>
  </div>
</div>

app/views/patients/edit.html.erb
<div class="max-w-xl mx-auto py-8 px-4 sm:px-6 lg:px-8">
  <div class="bg-white shadow-md rounded-lg p-6">
    <h2 class="text-2xl font-bold mb-4">Edit Patient</h2>
    <%= render 'form', patient: @patient %>
  </div>
</div>

app/views/patients/index.html.erb
<div class="max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:px-8">
  <h1 class="text-2xl font-bold mb-4">All Registered Patients</h1>

  <div class="space-y-4">
    <% @patients.each do |patient| %>
      <%= render patient %>
    <% end %>
  </div>
</div>

app/views/patients/new.html.erb
<div class="max-w-xl mx-auto py-8 px-4 sm:px-6 lg:px-8">
  <div class="bg-white shadow-md rounded-lg p-6">
    <h2 class="text-2xl font-bold mb-4">Register New Patient</h2>
    <%= render 'form', patient: @patient %>
  </div>
</div>

app/views/patients/show.html.erb
<div class="max-w-3xl mx-auto py-8 px-4 sm:px-6 lg:px-8">
  <div class="bg-white shadow-md rounded-lg p-6">
    <div class="mb-4">
      <h1 class="text-2xl font-bold">
        Patients Name: <%= @patient.full_name %>
      </h1>
    </div>

    <div class="mb-4">
      <% if @patient.date_of_birth %>
        <p class="text-gray-600">
          Age: <%= ((Time.zone.now - @patient.date_of_birth.to_time) / 1.year.seconds).floor %>
        </p>
      <% else %>
        <p class="text-gray-600">Date of birth not available</p>
      <% end %>
    </div>

    <div class="mb-4">
      <p class="font-medium">Allergy:</p>
      <% if @patient.allergies.present? %>
        <p class="text-gray-600"><%= @patient.allergies %></p>
      <% else %>
        <p class="text-gray-600">No known allergy</p>
      <% end %>
    </div>

    <div class="mb-4">
      <p class="font-medium">Chief Complaints:</p>
      <% if @patient.chief_complaints.present? %>
        <p class="text-gray-600"><%= @patient.chief_complaints %></p>
      <% else %>
        <p class="text-gray-600">Patient will describe on his/her own to doctor</p>
      <% end %>
    </div>

    <div class="mb-4">
      <p class="font-medium">Appointed to Dr. <%= @patient.doctor.full_name %></p>
      <% if @patient.appointment_date %>
        <p class="text-gray-600">on <%= @patient.appointment_date.strftime('%B %d, %Y at %I:%M%p') %></p>
      <% end %>
    </div>

    <div class="mb-4">
      <p class="font-medium">Registered by, <%= @patient.registered_by.full_name %></p>
    </div>

    <% if current_user.role == 'receptionist' && current_user == @patient.registered_by %>
      <div class="flex justify-end space-x-4">
        <div>
          <%= link_to "Edit", edit_patient_path, class: "bg-indigo-500 hover:bg-indigo-600 text-white font-medium py-2 px-4 rounded" %>
        </div>
        <div>
          <%= link_to "Delete", patient_path(@patient), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "bg-red-500 hover:bg-red-600 text-white font-medium py-2 px-4 rounded" %>
        </div>
      </div>
    <% end %>
  </div>
</div>